name: 'WordPress Theme Check Action'
description: 'Runs the Theme Check plugin against your theme'
author: 'The WordPress Contributors'
inputs:
  root-folder:
    description: 'The location of your theme'
    default: .
  accessible-ready:
    description: 'Whether to run the full accessibility tests'
    default: false
  ui-debug:
    description: 'More verbose logging; Creates a GIF'
    default: false
env:
  WP_ENV_PORT: 8888
  WP_ENV_TESTS_PORT: 8889
branding:
  icon: 'clipboard'  
  color: 'blue'
runs:
  using: 'node12'
  main: 'bin/program.js'
  post: 'github-post.js'