name: 'WordPress Theme Check Action'
description: 'Runs the Theme Check plugin against your theme'
author: 'The WordPress Contributors'
inputs:
  root-folder:
    description: 'The location of your theme'
    default: .
  accessible-ready:
    description: 'Whether to run the full accessibility tests'
    default: false
  ui-debug:
    description: 'More verbose logging; Creates a GIF'
    default: false
branding:
  icon: 'clipboard'  
  color: 'blue'
runs:
  using: 'composite'
  steps:
    - run: |
        echo Copying theme folder ...
        rsync -av --exclude=.git* ${{ inputs.root-folder }}/* ${{ github.action_path }}/test-theme
      shell: bash

    - run: cd ${{ github.action_path }} && npm install
      shell: bash

    - run: cd ${{ github.action_path }} && node bin/program.js --skip-folder-copy
      shell: bash